spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employeemanager
    name: root  
    password: banco123
   
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: null
    properties:
     dialect: org.hibernate.dialect.MySQL8Dialect